# WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY doBuild version. DO NOT EDIT THIS FILE
Version<-"23.09 (2023-09-16)"
VersionNumber<-"23.09"
SourceControlRevision<-"30d1ebb1792bdc3c667bc0f9405c0aec12b53751"
SourceControlDateDoc<-"2023-09-16"
SourceControlYearDoc<-"2023"
SourceControlMonthDoc<-"September"
SourceControlTimeDoc<-"23:27:16"
SourceControlVersion<-"2023-09-16 23:27:16 UTC (rev. 30d1ebb17)"
